### ISSUE TITLE
Can you add support for Zepto library ?

### ISSUE THREAD

**Issue by shidhincr** [visiongeist/toe.js#10]
Zepto is widely used in mobile devices since it's light weight. I think you've to add support for Zepto since Zepto lacks a proper touch based gestures and custom events.

I guess to give the support , changes will be very minimal.

**Comment by visiongeist** [comment]
support is now given through 3.0.1. You will find a toe.zepto.js file which works with zepto 1.0

**Comment by shidhincr** [comment]
Thanks lot
