### ISSUE TITLE
Windows 8 and IE10

### ISSUE THREAD

**Issue by coffeebite** [visiongeist/toe.js#3]
IE10 on Windows 8/Windows Phone 8 does not support ontouchstart events. Instead, it has its own proprietary events. More here.
http://msdn.microsoft.com/en-us/library/ie/hh673557(v=vs.85).aspx

What's the best way to support Windows Devices?

**Comment by EnzoMartin** [comment]
Running into this issue as well

**Comment by lhwparis** [comment]
pointer events are not proprietary they are just another solution to handle touch input and in my oppinion the better way over webkit touch events

**Comment by roele** [comment]
the following polyfill would might come in handy https://github.com/jquery/jquery-pointer-events

**Comment by fredgalvao** [comment]
I +1 this feature, and I'd be happy to help try and implement this for Windows Phone 8.
According to this [Windows Blog Post](http://blogs.windows.com/windows_phone/b/wpdev/archive/2012/11/15/adapting-your-webkit-optimized-site-for-internet-explorer-10.aspx), it shouldn't take much effort to make it simply "work": for each of the 3 touch<X> events, add a dupe for MSPointer<IE(X)> and voilá.
I see this feature as a very important one, considering that W3C took this implementation and abstraction of pointer events as the default. Sooner or later it should be done, I think.

PS: I've yet to try the polyfill above, maybe that already solves the problem.

**Comment by visiongeist** [comment]
@roele thanks I'll try this as soon as I can get my hand on a win8 device.
@fredgalvao shouldn't be to difficult though I don't have a win8 device to test it.

**Comment by fredgalvao** [comment]
I have the environment setup to emulate a Window Phone 8 alright. Spent some time understanding how toe.js works now (I used to in version 1.x, big changes came since then **{splendid job btw!}**), and I think it'll be a piece of cake to implement this. Gonna try my best and test.

**Comment by visiongeist** [comment]
was actually by a contribution
