### ISSUE TITLE
swipe doesnt work in Samsung Galaxy s3

### ISSUE THREAD

**Issue by benyitzhaki** [visiongeist/toe.js#7]
I have experienced issues only in this specific device. has anybody else experienced it?
it has been tested over 3 different phones.. all of them are having issues with the swipe event.

other devices are working without any problem (including galaxy s1, galaxy s2, galaxy ace, nexus 4, samasung defy+... just the galaxy s3 is having problems)

Thanks.

**Comment by visiongeist** [comment]
Does this still occur?
